### PR TITLE
Possible fix for duplicated confessions

### PR DESCRIPTION
**Pull request by NovAti0n**
Idk if this works

Let's hope

### CODE REVIEW

**Comment by NovAti0n** [comment]
Do confessions work properly now? Haven't seen a duplicated one in a while

**Comment by fdardenne** [comment]
> Do confessions work properly now? Haven't seen a duplicated one in a while

There is'nt duplicated message anymore ! But the approved confession in the admin channel is not deleted by the bot

**Comment by NovAti0n** [comment]
Didn't plan to delete the confessions in the admin channel at first. I can do that this afternoon.

**Comment by NovAti0n** [comment]
Since the duplicated confession is not a problem anymore, I'll close this PR and open a new one regarding the message deletion in the admin channel

**Pull request closed without merging**
